### ISSUE TITLE
관리자가 관리자 화면에서 글을 삭제할 때 포인트 부족 문제

### ISSUE THREAD

**Issue by 1Sam** [xpressengine/plugin-point#12]
관리자는 포인트에 상관없이 글을 삭제할 수 있어야 하지 않을까 생각합니다.
물론 포인트를 많이 부여해 놓고 사용해도 되겠지만....
관리자는 포인트에 상관없이 글 삭제를 할 수 있는 옵션을 추가해도 괜찮을 것 같습니다.

**Comment by xharpenParksuhyeon** [comment]
글 삭제 시 작성된 게시판의  `manage` 권한을 보유한 사용자가 진행한 거라면 포인트에 상관없이 진행되도록 코드를 수정했습니다.
 
<br>

 게시판에 대한 `manage` 권한
![image](https://user-images.githubusercontent.com/54769955/121844068-52651000-cd1e-11eb-8a2c-d6225831303e.png)
