### ISSUE TITLE
업데이트 후에도 ‘지금 수정사항 적용하기’가 나옵니다.

### ISSUE THREAD

**Issue by cansmile** [xpressengine/plugin-point#14]
![2020041300008](https://user-images.githubusercontent.com/459021/79126126-4dcf5f80-7dda-11ea-9177-b1b27714bde2.png)

**Comment by akasima** [comment]
네. 제가 업데이트 코드를 잘못 만들었나봐요. 
확인해 보겠습니다.

**Comment by woongbin** [comment]
해당 문제 수정 완료해서 1.0.6 버전에 반영 될 예정입니다.
감사합니다.
